# generated by datamodel-codegen:
#   filename:  hashcat_assets.json

from __future__ import annotations

from typing import List
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class HashcatAssetSchema(BaseModel):
    model_config = ConfigDict(
        from_attributes=True,
    )
    id: int = Field(..., title="id")
    task_uuid: UUID = Field(..., title="task_uuid")
    worker_id: str = Field(..., min_length=3, title="worker_id")
    files: List[str] = Field(..., title="files")
    created_at: AwareDatetime = Field(..., title="created_at")
