# generated by datamodel-codegen:
#   filename:  users.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import ConfigDict, RootModel


class Model(RootModel[Any]):
    model_config = ConfigDict(
        from_attributes=True,
    )
    root: Any


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    USER = "USER"
